language: python

matrix:
  include:
    - env: TOX_ENV=py38-django-30-es6
      python: 3.8
    - env: TOX_ENV=py38-django-22-es6
      python: 3.8
    - env: TOX_ENV=py38-django-111-es6
      python: 3.8
    - env: TOX_ENV=py37-django-30-es6
      python: 3.7
    - env: TOX_ENV=py37-django-22-es6
      python: 3.7
    - env: TOX_ENV=py37-django-111-es6
      python: 3.7
    - env: TOX_ENV=py36-django-30-es6
      python: 3.6
    - env: TOX_ENV=py36-django-22-es6
      python: 3.6
    - env: TOX_ENV=py36-django-111-es6
      python: 3.6
install:
- pip install tox


script: tox -e $TOX_ENV

cache: pip

# Setup Elasticsearch Environment
env:
  global:
    - ES_APT_URL=https://artifacts.elastic.co/packages/7.x/apt

before_install:
  - wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
  - echo "deb $ES_APT_URL stable main" | sudo tee -a /etc/apt/sources.list.d/elk.list
  - sudo apt-get remove --purge elasticsearch -y
  - sudo apt-get update && sudo apt-get install elasticsearch -y
  - sudo -i service elasticsearch restart

before_script:
  - wget -q --waitretry=1 --retry-connrefused -T 100 -O - http://127.0.0.1:9200
